MODUL 6 SULTHONI/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  Route::get('/profile/{id}', 'UserController@index')->name('profile');
  Route::get('/home', 'HomeController@index')->name('home');
  Route::get('/profile/edit/{id}','UserController@edit')->name('edit');
  Route::get('/post','PostController@create')->name('post');
  Route::post('/post', 'PostController@store')->name('post');
  Route::post('/comment', 'PostController@comment')->name('comment');
  Route::put('/profile/{id}', 'UserController@update');
  Route::get('/detail/{id}', 'PostController@show')->name('detailpost');
});

MODUL 6 SULTHONI/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $table = "posts";
    protected $fillable = ['caption','image', 'user_id'];

    // $user = DB::table('users')->get();
    // $user = DB::table($table)->where('user_id', auth()->id());

    public function user()
    {
      // code...
      return $this->belongsTo('App\User', 'user_id','id');
    }
    public function comments()
    {
      // code...
      return $this->hasMany('App\PostComment', 'post_id', 'id');
    }
}

MODUL 6 SULTHONI/app/PostComment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostComment extends Model
{
    //
    protected $table = 'post_comment';

    protected $fillable = ['user_id','post_id','comment'];

    public function user()
    {
      // code...
      return $this->belongsTo('App\User','user_id','id');
    }
    public function post()
    {
      // code...
      return $this->belongsTo('App\Post','post_id','id');
    }
}

MODUL 6 SULTHONI/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function post()
    {
      // code...
      return $this->hasMany('App\Post','user_id');
    }
}

MODUL 6 SULTHONI/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

MODUL 6 SULTHONI/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Auth;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user_id = Auth::user()->id;
        $data['posts'] = Post::all();
        return view('home',$data);
    }
    
}

MODUL 6 SULTHONI/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PostComment;
use App\Post;
use Carbon\Carbon;
use Auth;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('addpost');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('addpost');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $file = $request->file('image');
        $namafile = $file->getClientOriginalName();
        $file->move(public_path('/'), $namafile);

        $post = Post::create(
          array('user_id'=>Auth::user()->id,
            'caption' => $request->caption,
            'image' => $namafile,
            'created_by' => Carbon::now(),
            'updated_by' => Carbon::now(),
          )
        );
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $data['post'] = Post::with(['user', 'comments.user'])->where('id', $id)->first();

      return view('detailpost', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function comment(Request $request)
    {
      // code...
      $comment = PostComment::create([
        'user_id' => Auth::user()->id,
        'post_id' =>$request->post_id,
        'comment' =>$request->comment,
        'created_by' =>Carbon::now(),
        'updated_by' =>Carbon::now(),
      ]);
      return back();
    }
}

MODUL 6 SULTHONI/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use app\User;
use Carbon\Carbon;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        //
        $get['user'] = User::withCount('post')->where('id',$id)->first();

        return view('profile',$get);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $get['user'] = Auth::user();
        return view('edit',$get);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = User::find($id);
        $user->title = $request->title;
        $user->description = $request->description;
        $user->url = $request->url;
        $user->updated_at = Carbon::now();

        if ($request->avatar != null) {
            $file = $request->file('avatar');
            $file_name = $file->getClientOriginalName();
            $file->move(public_path('/'), $file_name);

            $user->avatar = $file_name;
        }

        $user->save();
        return redirect('/profile/' . $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

MODUL 6 SULTHONI/resources/views/addpost.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Add New Post</h2>
            </div>
        </div>
        <div class="row justify-content-sm-center mt-5">
            <div class="col-sm-6">
                <form action="{{ url('post') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Post Caption</label>
                        <textarea class="form-control" name="caption" id="caption"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Post Image</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="image" id="image">
                            <label class="custom-file-label" for="image">Pilih Gambar</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Post</button>
                </form>
            </div>
        </div>
    </div>
@endsection

MODUL 6 SULTHONI/resources/views/detailpost.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <img src="{{ asset('' . $post->image) }}" class="post-image-detail">
            </div>
            <div class="col-sm-6">
                <div class="row col-sm-12">
                    <a href="{{ url('profile/' . $post->user->id) }}">
                        <img src="{{ asset('' . $post->user->avatar) }}" class="avatar">
                    </a>
                    <span class="post-user flex">{{ $post->user->name }}</span>
                </div>
                <hr>
                <div class="row col-sm-12 text-left">
                    <span class="post-user">{{ $post->user->email }}</span>
                    <span class="post-caption">{{ $post->caption }}</span>
                </div>
                @foreach($post->comments as $comment)
                    <div class="row col-sm-12 text-left">
                        <span class="post-user">{{ $comment->user->email }}</span>
                        <span class="post-caption">{{ $comment->comment }}</span>
                    </div>
                @endforeach
                <hr>
                <div class="row col-sm-12 text-left">
                <img  src="/assets/like.png" style="padding: 10px 0"></img>
                <img  src="/assets/comment.png" style="padding: 10px 15px"></img>
                </div>
                <div class="row col-sm-12 text-left">
                    <span class="post-user">{{ $post->likes }} Likes</span>
                </div>
                <form action="{{ url('comment') }}" method="POST">
                    <div class="row col-sm-12">
                        @csrf
                        <input type="hidden" name="post_id" value="{{ $post->id }}">
                        <div class="input-group mt-2">
                            <input type="text" class="form-control" name="comment" placeholder="Add a comment...">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Post</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

MODUL 6 SULTHONI/resources/views/edit.blade.php
  @extens('layouts.app')
  @section('content')
      <div class="container">
          <div class="row">
              <div class="col-sm-12 text-center">
                  <h2>Edit Profile</h2>
              </div>
          </div>
          <div class="row justify-content-sm-center mt-4">
              <div class="col-sm-6">
                  <form action="{{ url('profile/' . $user->id) }}" method="POST" enctype="multipart/form-data">
                      @csrf
                      @method('PUT')
                      <div class="form-group">
                          <label>Title</label>
                          <input type="text" class="form-control" name="title" id="title" value="{{ $user->title }}">
                      </div>
                      <div class="form-group">
                          <label>Description</label>
                          <input type="text" class="form-control" name="description" id="description" value="{{ $user->description }}">
                      </div>
                      <div class="form-group">
                          <label>URL</label>
                          <input type="text" class="form-control" name="url" id="url" value="{{ $user->url }}">
                      </div>
                      <div class="form-group">
                          <label>Profile Image</label>
                          <div class="custom-file">
                              <input type="file" class="custom-file-input" name="avatar" id="avatar">
                              <label class="custom-file-label" for="image">Choose file</label>
                          </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Save Profile</button>
                  </form>
              </div>
          </div>
      </div>
  @endsection

MODUL 6 SULTHONI/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                      @if(isset($posts))
                        @foreach($posts as $post)
                          <div class="card">
                            <div class="card-header">
                              <img src="{{asset(''.$post->user->avatar)}}" alt="avatar" class="avatar">
                              <span class="post-user">{{ $post->user->name}}</span>
                            </div>
                            <div class="card-body">
                              @if(session('status'))
                              <div class="alert alert-success" role="alert">
                                  {{ session('status') }}
                              </div>
                              @endif
                              <a href="{{url('detail/'.$post->id)}}"><img src="{{asset(''.$post->image)}}" alt="{{asset(''.$post->image)}}" class="post-image"></a>
                            </div>
                            <div class="card-footer">
                              <div class="col-sm-12 text-left">
                                <a href=""><img src="assets/like.png" alt="like"></a>
                                <a href=""><img src="assets/comment.png" alt="comment"></a>
                              </div>
                              <div class="col-sm-12 text-left">
                                <span class="post-user">{{$post->user->email}}</span>
                              </div>
                              <div class="col-sm-12 text-left">
                                <span class="post-caption">{{$post->caption}}</span>
                              </div>
                              @isset($post->comments)
                              @foreach($post->comments as $comment)
                                  <div class="col-sm-12 text-left">
                                      <span class="post-user">{{ $comment->user->email }}</span>
                                      <span class="post-caption">{{ $comment->comment }}</span>
                                  </div>
                              @endforeach
                              @endisset
                              <div class="col-sm-12">
                                    <form action="{{ url('comment') }}" method="POST">
                                        @csrf
                                        <input type="hidden" name="post_id" value="{{ $post->id }}">
                                        <div class="input-group mt-2">
                                            <input type="text" class="form-control" name="comment"
                                                   placeholder="Add a comment...">
                                            <div class="input-group-append">
                                                <button class="btn btn-outline-secondary" type="submit">Post</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                          </div>
                      @endforeach
                    @endif

                    <!-- You are logged in! -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

MODUL 6 SULTHONI/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
    <!-- Styles -->


</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <a href="{{ url('/home') }}"><img src="{{asset('EAD.png')}}" alt="ead-nav" style="width:150px;" ></a>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <!-- <div class="dropdwon-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                </div> -->
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                    <a class = "dropdown-item" href="{{ url('profile/'.Auth::user()->id) }}" onclick="">
                                      Profile
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

MODUL 6 SULTHONI/resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row mb-lg-5">
            <div class="col-sm-4 text-center pt-lg-5">
                <img src="{{ asset('' . $user->avatar) }}" class="avatar-profile" alt="avatar">
            </div>
            <div class="col-sm-8">
                <div class="row mt-4 mb-4">
                    <div class="col-sm-8 post-user" style="padding: 0">
                        {{ $user->name }}
                    </div>
                    <div class="col-sm-4 text-right">
                        <a href="{{ route('post') }}" class="text-right">Add New Post</a>
                    </div>
                </div>
                <div class="row">
                    <a href="{{ url('profile/edit/'.$user->id) }}">Edit Profile</a>
                </div>
                <div class="row mb-4">{{ $user->post_count }} Posts</div>
                <div class="row post-user">{{ $user->title }}</div>
                <div class="row">{{ $user->description }}</div>
                <div class="row">
                    <a href="{{ $user->url }}">{{ $user->url }}</a>
                </div>
            </div>
        </div>
        @foreach($user->post as $post)
            @if(($loop->iteration % 3 - 1) == 0)
                <div class="row">
                    @endif
                    <div class="col-sm-4">
                        <a href="{{ url('detail/' . $post->id) }}">
                            <img src="{{ asset('' . $post->image) }}" class="post-image-profile"
                             alt="{{ asset('' . $post->image) }}">
                        </a>
                    </div>
                    @if($loop->iteration % 3 == 0)
                </div>
            @endif
        @endforeach
    </div>
    </div>
@endsection